export const actionCapabilities = {
  addProductSuperBdd: {
    id: "add-product-superbdd",
    label: "Enable the SuperBDD adapter bundle",
    kind: "mutation",
    actor: "developer",
    surface: "eac add product/superbdd",
    risk: "medium",
    auth: "none",
    boundary: "updates EAC configuration so product/superbdd is enabled without creating product contract artifacts",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  initEnabledAdapters: {
    id: "init-enabled-adapters",
    label: "Scaffold artifacts for enabled adapters",
    kind: "mutation",
    actor: "developer",
    surface: "eac init",
    risk: "medium",
    auth: "none",
    boundary: "creates missing starter artifacts for enabled adapters and skips existing files unless forced",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  checkRepoContract: {
    id: "check-repo-contract",
    label: "Validate the repository contract",
    kind: "verification",
    actor: "developer/CI",
    surface: "eac check",
    risk: "medium",
    auth: "none",
    boundary: "loads configured adapters, builds graph evidence, applies waivers, and fails on unwaived errors",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  rejectStarterPlaceholders: {
    id: "reject-starter-placeholders",
    label: "Reject generated starter product placeholders",
    kind: "verification",
    actor: "developer/CI",
    surface: "product/manifest adapter diagnostics",
    risk: "medium",
    auth: "none",
    boundary: "fails product checks while generated eacStarter placeholders remain in the manifest",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  resolveOfficialAdapters: {
    id: "resolve-official-adapters",
    label: "Resolve official adapter selections",
    kind: "verification",
    actor: "developer",
    surface: "eac.config.ts adapters list",
    risk: "medium",
    auth: "none",
    boundary: "configured built-in adapter IDs resolve through the registry and unknown IDs fail fast",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  validateProductSuperBdd: {
    id: "validate-product-superbdd",
    label: "Validate Capability to Action product spine",
    kind: "verification",
    actor: "developer/CI",
    surface: "product/superbdd adapter",
    risk: "medium",
    auth: "none",
    boundary: "compiles manifest and Cucumber evidence into one product graph spine",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  validateArchitectureMermaid: {
    id: "validate-architecture-mermaid",
    label: "Validate Mermaid architecture sources",
    kind: "verification",
    actor: "developer/CI",
    surface: "architecture/mermaid adapter",
    risk: "low",
    auth: "none",
    boundary: "discovers configured Mermaid files, parses them, and contributes architecture graph nodes",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  validateDesignReact: {
    id: "validate-design-react",
    label: "Validate React design-system contracts",
    kind: "verification",
    actor: "developer/CI",
    surface: "design/react adapter",
    risk: "medium",
    auth: "none",
    boundary: "validates configurable React design-system token, taxonomy, registry, and usage-boundary evidence",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  validateDataSupabase: {
    id: "validate-data-supabase",
    label: "Validate Supabase data contracts",
    kind: "verification",
    actor: "developer/CI",
    surface: "data/supabase adapter",
    risk: "medium",
    auth: "none",
    boundary: "validates static Supabase env, generated type, migration, and integration evidence without live provider access",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  validateInfraTerraform: {
    id: "validate-infra-terraform",
    label: "Validate Terraform infrastructure contracts",
    kind: "verification",
    actor: "developer/CI",
    surface: "infra/terraform adapter",
    risk: "medium",
    auth: "none",
    boundary: "validates static Terraform source, variable, provider, script, and ownership-boundary evidence without plan/apply",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  validateDeployCloudflare: {
    id: "validate-deploy-cloudflare",
    label: "Validate Cloudflare deployment contracts",
    kind: "verification",
    actor: "developer/CI",
    surface: "deploy/cloudflare adapter",
    risk: "medium",
    auth: "none",
    boundary: "validates static Wrangler config, deploy script, env prerequisite, and optional CI evidence without live deploy",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  exportPublicApi: {
    id: "export-public-api",
    label: "Export public adapter API surface",
    kind: "verification",
    actor: "adapter consumer",
    surface: "src/index.ts",
    risk: "medium",
    auth: "none",
    boundary: "exports official adapters and option types needed by external configs and packages",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  loadAdapterOptions: {
    id: "load-adapter-options",
    label: "Load adapter option namespaces",
    kind: "verification",
    actor: "developer",
    surface: "eac.config.ts",
    risk: "medium",
    auth: "none",
    boundary: "top-level config namespaces and per-selection options route to the intended built-in adapters",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
  packageRelease: {
    id: "package-release",
    label: "Package release assets",
    kind: "mutation",
    actor: "maintainer",
    surface: "scripts/package-release.mjs",
    risk: "medium",
    auth: "maintainer git and GitHub access",
    boundary: "validates SemVer, builds the binary archive, and writes a checksum for GitHub release upload",
    workflow: null,
    verification: { required: ["bdd", "unit"] },
  },
} as const;

export const productCapabilities = {
  eacOnboarding: {
    id: "eac-onboarding",
    label: "EAC SuperBDD onboarding",
    tag: "@capability.eac-onboarding",
    cucumberFeatures: ["features/eac-onboarding.feature"],
    requiredActions: [
      "add-product-superbdd",
      "init-enabled-adapters",
      "check-repo-contract",
      "reject-starter-placeholders",
    ],
    workflows: [],
  },
  officialAdapterPack: {
    id: "official-adapter-pack",
    label: "Official EAC adapter pack",
    tag: "@capability.official-adapter-pack",
    cucumberFeatures: ["features/eac-adapter-pack.feature"],
    requiredActions: [
      "resolve-official-adapters",
      "validate-product-superbdd",
      "validate-architecture-mermaid",
      "validate-design-react",
      "validate-data-supabase",
      "validate-infra-terraform",
      "validate-deploy-cloudflare",
    ],
    workflows: [],
  },
  publicApi: {
    id: "public-api",
    label: "Public adapter and configuration API",
    tag: "@capability.public-api",
    cucumberFeatures: ["features/eac-public-api.feature"],
    requiredActions: ["export-public-api", "load-adapter-options"],
    workflows: [],
  },
  releaseDistribution: {
    id: "release-distribution",
    label: "Release distribution",
    tag: "@capability.release-distribution",
    cucumberFeatures: ["features/eac-release-distribution.feature"],
    requiredActions: ["package-release"],
    workflows: [],
  },
} as const;

export const userActionWorkflows = {} as const;
